/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import view.AddNatPerson;
import view.AddCompany;
import view.AddAccount;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.WindowConstants;
import bussiness.BranchOffice;

/**
 *
 * @author user
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        branchOfficeLbl.setText("Está en la sucursal "+BranchOffice.getInstance().getName());
        addressLbl.setText(BranchOffice.getInstance().getAddress()+", "+BranchOffice.getInstance().getCity());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        openningAccountBtn = new javax.swing.JButton();
        closingAccountBtn = new javax.swing.JButton();
        newNatPerBtn = new javax.swing.JButton();
        withdrawalBtn = new javax.swing.JButton();
        newCompanyBtn = new javax.swing.JButton();
        branchOfficeLbl = new javax.swing.JLabel();
        addressLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bienvenido a StarBank");

        openningAccountBtn.setText("Abrir cuenta");
        openningAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openningAccountBtnActionPerformed(evt);
            }
        });

        closingAccountBtn.setText("Cerrar cuenta");
        closingAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closingAccountBtnActionPerformed(evt);
            }
        });

        newNatPerBtn.setText("Agregar persona natural");
        newNatPerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newNatPerBtnActionPerformed(evt);
            }
        });

        withdrawalBtn.setText("Consignaciones y Retiros");
        withdrawalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawalBtnActionPerformed(evt);
            }
        });

        newCompanyBtn.setText("Agregar empresa");
        newCompanyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCompanyBtnActionPerformed(evt);
            }
        });

        branchOfficeLbl.setText(" ");

        addressLbl.setAlignmentX(0.5F);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 49, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(branchOfficeLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addressLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(openningAccountBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(closingAccountBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newNatPerBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(newCompanyBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(withdrawalBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addComponent(branchOfficeLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addressLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(openningAccountBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closingAccountBtn)
                .addGap(18, 18, 18)
                .addComponent(newNatPerBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newCompanyBtn)
                .addGap(18, 18, 18)
                .addComponent(withdrawalBtn)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newCompanyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCompanyBtnActionPerformed
        AddCompany comp = new AddCompany();
        comp.setVisible(true);
        comp.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
    }//GEN-LAST:event_newCompanyBtnActionPerformed

    private void newNatPerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newNatPerBtnActionPerformed
        AddNatPerson cuadro1 = new AddNatPerson();
        cuadro1.setVisible(true);   
        cuadro1.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
    }//GEN-LAST:event_newNatPerBtnActionPerformed

    private void closingAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closingAccountBtnActionPerformed
        DeactivateAccount deac = new DeactivateAccount();
        deac.setVisible(true);
        deac.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
    }//GEN-LAST:event_closingAccountBtnActionPerformed

    private void openningAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openningAccountBtnActionPerformed
        AddAccount add = new AddAccount();
        add.setVisible(true);
        add.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
    }//GEN-LAST:event_openningAccountBtnActionPerformed

    private void withdrawalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawalBtnActionPerformed
        WithdrawalForm wit = new WithdrawalForm();
        wit.setVisible(true);
        wit.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
    }//GEN-LAST:event_withdrawalBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLbl;
    private javax.swing.JLabel branchOfficeLbl;
    private javax.swing.JButton closingAccountBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton newCompanyBtn;
    private javax.swing.JButton newNatPerBtn;
    private javax.swing.JButton openningAccountBtn;
    private javax.swing.JButton withdrawalBtn;
    // End of variables declaration//GEN-END:variables
}
